### ISSUE TITLE
下载KeyError问题

### ISSUE THREAD

**Issue by xing-yv** [xing-yv/fanqie-novel-download#1]
下载报错：
Traceback (most recent call last):
  File "番茄小说下载v1.0-PR.py", line 272, in <module>
  File "番茄小说下载v1.0-PR.py", line 198, in download_novel
KeyError: 'content'
[26036] Failed to execute script '番茄小说下载v1.0-PR' due to unhandled exception!

**Comment by xing-yv** [comment]
已复现，正在尝试解决
